# Generated by Django 4.2.1 on 2023-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='company',
        ),
        migrations.CreateModel(
            name='CompanyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(related_name='companydistribution', to='asset_management.company')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ManyToManyField(related_name='CompanyName', to='asset_management.company'),
        ),
    ]
