# Generated by Django 4.2.1 on 2023-07-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_remove_asset_company_companydistribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=30)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='employees',
            field=models.ManyToManyField(related_name='employee', to='asset_management.employee'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyDistribution',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='devices',
            field=models.ManyToManyField(related_name='device', to='asset_management.device'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.company'),
        ),
    ]
