# Generated by Django 4.2.1 on 2023-07-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_device_devicelog_remove_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.company'),
        ),
    ]
