# Generated by Django 4.2.1 on 2023-07-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_deviceassignment_remove_device_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.employee'),
        ),
    ]
