# Generated by Django 4.2.1 on 2023-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0008_alter_device_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
